apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-sync-cronjob-sms
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-sync-container-sms
            image: 905418348110.dkr.ecr.eu-central-1.amazonaws.com/unipol-stargate-euc1-archiviazione-comunicazioni-ecr-dev:batch-sync
            imagePullPolicy: Always
            env:
                - name: CHANNEL_ID
                  value: "synchJobSms"
          restartPolicy: OnFailure


---


apiVersion: batch/v1
kind: CronJob
metadata:
  name: batch-sync-cronjob-email
spec:
  schedule: "*/1 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: batch-sync-container-email
            image: 905418348110.dkr.ecr.eu-central-1.amazonaws.com/unipol-stargate-euc1-archiviazione-comunicazioni-ecr-dev:batch-sync
            imagePullPolicy: Always
            env:
                - name: CHANNEL_ID
                  value: "synchJobEml"
          restartPolicy: OnFailure

