---
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-sync-job-email
spec:
  template:
    spec:
      serviceAccountName: s3
      containers:
      - name: batch-sync-container-email
        image: 905418348110.dkr.ecr.eu-central-1.amazonaws.com/unipol-stargate-euc1-archiviazione-comunicazioni-ecr-dev:batch-sync
        imagePullPolicy: Always
        env:
          - name: CHANNEL_ID
            value: "synchJobEml"
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-arch-sostitutivo-sms-job
spec:
  template:
    spec:
      serviceAccountName: s3
      containers:
      - name: batch-arch-sostitutivo-container
        image: 905418348110.dkr.ecr.eu-central-1.amazonaws.com/unipol-stargate-euc1-archiviazione-comunicazioni-ecr-dev:batch-sostitutivo
        imagePullPolicy: Always
        env:
          - name: CHANNEL_ID
            value: "SMS"
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-arch-sostitutivo-email-job
spec:
  template:
    spec:
      serviceAccountName: s3
      containers:
      - name: batch-arch-sostitutivo-container
        image: 905418348110.dkr.ecr.eu-central-1.amazonaws.com/unipol-stargate-euc1-archiviazione-comunicazioni-ecr-dev:batch-sostitutivo
        imagePullPolicy: Always
        env:
          - name: CHANNEL_ID
            value: "EMAIL"
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-documentale-sms-job
spec:
  template:
    spec:
      serviceAccountName: s3
      containers:
      - name: batch-documentale-sms-container
        image: 905418348110.dkr.ecr.eu-central-1.amazonaws.com/unipol-stargate-euc1-archiviazione-comunicazioni-ecr-dev:batch-documentale
        imagePullPolicy: Always
        env:
          - name: CHANNEL_ID
            value: "SMS"
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-documentale-email-job
spec:
  template:
    spec:
      serviceAccountName: s3
      containers:
      - name: batch-documentale-email-container
        image: 905418348110.dkr.ecr.eu-central-1.amazonaws.com/unipol-stargate-euc1-archiviazione-comunicazioni-ecr-dev:batch-documentale
        imagePullPolicy: Always
        env:
          - name: CHANNEL_ID
            value: "EMAIL"
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: batch-sync-job-sms
spec:
  template:
    spec:
      serviceAccountName: s3
      containers:
      - name: batch-sync-container-sms
        image: 905418348110.dkr.ecr.eu-central-1.amazonaws.com/unipol-stargate-euc1-archiviazione-comunicazioni-ecr-dev:batch-sync
        imagePullPolicy: Always
        env:
          - name: CHANNEL_ID
            value: "synchJobSms"
      restartPolicy: OnFailure
